/**
 * Real cross-chain join (docs/adr/0013) -- the same conceptual pattern as
 * `contracts/cross-chain-join.ts` (independently read two chains, join by a shared key, no
 * bridge), upgraded from "Midnight side via the compact-runtime simulator" to "Midnight side via a
 * genuine deploy + circuit call on the local devnet": a real deployed contract, a real ZK proof
 * generated by the local proof server, a real submitted and confirmed transaction. The EVM side is
 * unchanged -- still a real anvil transaction via Foundry, per docs/adr/0007.
 *
 * Prerequisites: the local devnet running (`/midnight-tooling:devnet start`, or
 * `docker compose -f .midnight-devnet/devnet.yml up -d` from the repo root), `anvil` running on
 * 127.0.0.1:8545, and `cross-chain/` compiled (`cd cross-chain && forge build`).
 *
 * Run: npx tsx cross-chain-join-real.ts [level]
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { deployAndProveThreshold } from './devnet-deploy.js';

const ANVIL_RPC = process.env.ANVIL_RPC ?? 'http://127.0.0.1:8545';
// Foundry/anvil's well-known, publicly documented default dev key for account #0 -- safe ONLY
// against a local anvil devnet, never anything real.
const ANVIL_DEPLOYER_KEY = '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';
const RANK_THRESHOLD = 5n;
const CROSS_CHAIN_DIR = path.join(import.meta.dirname, '..', '..', 'cross-chain');

const toHex = (b: Uint8Array) => Buffer.from(b).toString('hex');

function cast(...args: string[]): string {
  return execFileSync('cast', args, { encoding: 'utf8' }).trim();
}

function forge(...args: string[]): string {
  return execFileSync('forge', args, { encoding: 'utf8', cwd: CROSS_CHAIN_DIR }).trim();
}

function artifactPath(): string {
  return path.join(CROSS_CHAIN_DIR, 'out', 'ChampionBadge.sol', 'ChampionBadge.json');
}

/** Same EVM side as cross-chain-join.ts -- deploy fresh, mint only if the Midnight side qualified,
 *  read the tier back independently. `evmAddress` is a demo join key, not a real derivation. */
function runEvmSide(evmAddress: string, qualifies: boolean): { deployedAt: string; tier: number } {
  let artifact = JSON.parse(readFileSync(artifactPath(), 'utf8'));
  if (!artifact.bytecode?.object) {
    forge('build');
    artifact = JSON.parse(readFileSync(artifactPath(), 'utf8'));
  }

  const deployOut = cast('send', '--rpc-url', ANVIL_RPC, '--private-key', ANVIL_DEPLOYER_KEY, '--create', artifact.bytecode.object, '--json');
  const deployedAt = JSON.parse(deployOut).contractAddress as string;

  if (qualifies) {
    cast('send', '--rpc-url', ANVIL_RPC, '--private-key', ANVIL_DEPLOYER_KEY, deployedAt, 'mint(address,uint8)', evmAddress, '1');
  }

  const tierHex = cast('call', '--rpc-url', ANVIL_RPC, deployedAt, 'tier(address)(uint8)', evmAddress);
  return { deployedAt, tier: Number.parseInt(tierHex, 10) };
}

async function main() {
  const level = BigInt(process.argv[2] ?? '10'); // try `npx tsx cross-chain-join-real.ts 2` to see it fail the threshold
  console.log(`Midnight side: deploying MidnightPool and running the real proveThreshold(level >= ${RANK_THRESHOLD}) circuit on the local devnet...`);
  const { contractAddress, commitTxId, proveTxId, qualifies, pk } = await deployAndProveThreshold(level, 0n, RANK_THRESHOLD, false);
  const evmAddress = '0x' + toHex(pk).slice(0, 40);

  console.log(`Midnight side: contract ${contractAddress}, commitStats tx ${commitTxId}, proveThreshold tx ${proveTxId}`);
  console.log(`Midnight side: proveThreshold(level >= ${RANK_THRESHOLD}) -> ${qualifies} (level itself never disclosed)`);
  console.log(`Join key (Midnight pk, truncated to an EVM-shaped address): ${evmAddress}`);

  const evm = runEvmSide(evmAddress, qualifies);
  console.log(`EVM side: ChampionBadge deployed at ${evm.deployedAt}, tier(${evmAddress}) = ${evm.tier}`);

  const joined = {
    midnightContractAddress: contractAddress,
    midnightPublicKey: '0x' + toHex(pk),
    provenAboveThreshold: qualifies,
    evmAddress,
    evmTier: evm.tier,
  };
  console.log('\nJoined cross-chain view:', JSON.stringify(joined, null, 2));

  if (qualifies !== (evm.tier > 0)) {
    throw new Error('Join is inconsistent: the two chains disagree on qualification. This should never happen.');
  }
  console.log('\nOK — join is consistent: EVM tier reflects exactly the Midnight-disclosed qualification, both sides real.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
